#:kivy 2.3.0


<ScanImage>:
    name: "main_menu"

    BoxLayout:
        id: "nav_bar"
        orientation: "vertical"
        size_hint_x: 0.25 # This makes the BoxLayout take up 25% of its parent's width
        pos_hint: {"x": 0, "center_y": .60}
        spacing: 70 

        canvas.before:
            Color:
                #rgba: 0.3, 0.4, 0.9, 1  
                rgba: 0, 0, 1, 1  
            Rectangle:
                size: self.size
       # AnchorLayout:
            #anchor_y: 'top'  # This will position the buttons at the top of the BoxLayout
        Button:
            markup: True
            text: '[b]Upload Image[/b]'
            size_hint_x: 0.5
            size_hint_y: None
            pos_hint: {'x':0.50, "y": 1}     
            color: [0,0,1,1]     
            background_normal: ''
            background_down: ''  
          
            on_touch_down: if self.collide_point(*args[1].pos): root.manager.current = 'scan_img'

        Button:
            markup: True
            text: '[b]View Record[/b]'
             
            pos_hint: {'x':0.5, 'y':0.6}
            color: [1,1,1,1]
            background_normal: ''
            background_down: ''
            background_color: 0, 0, 1, 1
            size_hint_x: 0.5
            size_hint_y: None           
            on_press:
                root.manager.current = 'view_rec'
        
        Button:
            markup: True
            text: '[b]Logout[/b]'
             
            pos_hint: {'x':0.5, 'y':0.2}
            color: [1,1,1,1]
            background_normal: ''
            background_down: ''
            background_color: 0, 0, 1, 1
            size_hint_x: 0.5
            size_hint_y: None           
            on_press:
                root.manager.current = 'login'

       
    BoxLayout:
        id: main_area
        orientation: 'vertical'
        size_hint_x: 0.75
        pos_hint: {'x':0.25}

        canvas.before:
            Color: 
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos

        BoxLayout:
            orientation: 'vertical'
            padding: 10
            spacing: 10
            

            FloatLayout:
                Label: 
                    text: "[b]Upload Image[/b]"
                    markup: True
                    font_size: 35
                    pos_hint: {'center_x': 0.11,'center_y': 0.95}
                    color: 0, 0, 1, 1
                Label: 
                    text: "[i]Supported Formats: jpg, jpeg, png, DICOM\nDigital image must be of minimum size of 512x512 pixels[/i]"
                    markup: True
                    font_size: 26
                    pos_hint: {'center_x': 0.32,'center_y': 0.87}
                    color: 192/255, 192/255, 192/255, 1    
                Image:
                    id: image
                    size_hint: .45, .65
                    pos_hint: {'center_x': 0.35,'center_y': 0.40}
                    source: "assets/jpg.png"
                    # id: image
                    # pos_hint: {'center_x': .5, 'y': -.4}
                    # border: [10, 10, 10, 10]
                    # size_hint: 0.33, 0.98
                    # allow_stretch: True
                    # keep_ratio: True
                Image:
                    size_hint: .03, .03
                    pos_hint: {'center_x': 0.76,'center_y': 0.60}
                    source: "assets/jpg.png"
                Button:
                    text: "Upload Image"
                    size_hint: .13, .05
                    pos_hint: {'center_x': 0.84,'center_y': 0.60}
                    background_normal: ''
                    background_color: 0, 128/255, 1, 1
                    on_press: root.load_image()

                MDRectangleFlatButton:
                    text: "[b]Process Image[/b]"
                    font_size: 30
                    size_hint: .18, .06
                    pos_hint: {'center_x': 0.83,'center_y': 0.32}
                    on_press: root.process_image()