#:kivy 2.3.0
# <HoverLabel@Label+HoverBehavior>
#     on_enter: self.color = 0.8, 0.2, 1, 1
#     on_leave: self.color = 0, 0, 0, 1


<ViewRecords>:
    name: "main_menu"
    data_items: [] 

    BoxLayout:
        id: "nav_bar"
        orientation: "vertical"
        size_hint_x: 0.25 # This makes the BoxLayout take up 25% of its parent's width
        pos_hint: {"x": 0, "center_y": .60}
        spacing: 70 

        canvas.before:
            Color:
                #rgba: 0.3, 0.4, 0.9, 1  
                rgba: 0, 0, 1, 1  
            Rectangle:
                size: self.size
       # AnchorLayout:
            #anchor_y: 'top'  # This will position the buttons at the top of the BoxLayout
        
        Button:
            markup: True
            text: '[b]Upload Image[/b]'     
            font_size: '25sp'    
            pos_hint: {'x':0.50, 'y': 1}
            color: [1, 1, 1, 1]
            background_color: (0,0,1,1)
            size_hint_x: 0.5
            size_hint_y: None
            background_normal: ''
            background_down: ''
            on_press:
                root.manager.current = 'scan_img'  

       
        Button:
            markup: True
            text: '[b]View Record[/b]'
            font_size: '25sp'
            pos_hint: {'x':0.50, 'y':0.6}
            color: [0, 0, 1, 1]
            size_hint_x: 0.5
            size_hint_y: None
            background_normal: ''
            background_down: ''
            on_press:
                root.manager.current = 'view_rec'    
        
        Button:
            markup: True
            text: '[b]Logout[/b]'
            font_size: '25sp'
            pos_hint: {'x':0.50, 'y':0.2}
            color: [1, 1, 1, 1]
            background_color: (0,0,1,1)
            size_hint_x: 0.5
            size_hint_y: None
            background_normal: ''
            background_down: ''
            on_press:
                root.logout_popup() 
                    
    BoxLayout:
        id: main_area
        orientation: 'horizontal'
        size_hint_x: 0.75
        pos_hint: {'x':0.25, 'y':0.8}
        canvas.before:
            Color: 
                rgba: 1, 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
                
        BoxLayout:
            id: search_section
            size_hint_y: None
            height: '80dp'
            padding: {'10dp', '20dp'}  # Apply padding only to the top and bottom

            canvas.before:
                Color: 
                    rgba: 1, 1, 1, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
            TextInput:
                id: search_input
                multiline: False
                hint_text: 'Enter patient id here'
                height: '30dp'  # Set a specific height for the TextInput
                write_tab: False
                multiline: False
            
           
            Button:
                id: search_button
                markup: True
                text: "[b]Search[/b]"
                font_size: 15
                height: '30dp'
                background_normal: '' 
                background_color: [0,0,1,1]
                on_press: root.search_button()
            
    #result layout
    FloatLayout:
        Label:
            id: search_result
            color: [0,0,1,1] 
            font_size: 32
            bold: True
            pos_hint: {'center_x': 0.59, 'center_y': 0.75}
            
        

    #column title
    FloatLayout:
        Label:
            id: result_label
            color: [0,0,1,1]
            font_size: 28
            bold: True
            pos_hint: {'center_x': 0.54, 'center_y': 0.67}
            
        Label:
            id: date_label
            color: [0,0,1,1]
            font_size: 28
            bold: True
            pos_hint: {'center_x': 0.64, 'center_y': 0.67}
            
    
    BoxLayout:
        #id: search_result_layout
        orientation: "vertical"
        size_hint: 0.2, 0.5  
        pos_hint: {'x': 0.5, 'y': 0.12}  

        BoxLayout:
            RecycleView:
                viewclass: 'Button' 
                #data: [{'text': f"{str(x[3])}                        {str(x[2])}", 'on_release': lambda x=x: root.result_popup(x[1])} for x in root.data_items]
                data: [{'text': f"{str(x[3])} {str(x[2])}", 'on_release': lambda x=x, i=i: root.result_popup(x[1], i)} for i, x in enumerate(root.data_items)]                        
                #data: [{'text': f"{str(x[3])}                        {str(x[2])}", 'on_release': lambda x=x: root.record_clicked(x[1])} for x in root.data_items]

                RecycleBoxLayout:
                    id: search_result_layout
                    cols: 1
                    default_size: dp(2000), dp(80)
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
                    multiselect: False
                    touch_multiselect: False
                    spacing: dp(20)

    
        
        

        

      
      